### ISSUE TITLE
Issue with Owner

### ISSUE THREAD

**Issue by Incrested** [auroraware/bolt#2]
Hey, @d-nni3l !

Just a side note, @d-nni3l doesn't know how to code. 11 of his 15 repositories on GitHub (see https://github.com/d-nni3l) are forks, meaning he copied the code from others. One of which is my own (https://github.com/d-nni3l/miku-chan was copied from https://github.com/incrested/miku-chan).

His group, Aurora Software on GitHub (view at https://github.com/auroraware) has one project, which I can't hate on but it's "bolt" software has nothing in it but a license, readme, and a Jekyll configuration file (_config.yml). This group is also on GitLab (view at https://gitlab.com/auroraware), however, it is empty. If this seems like a surprise, it's the same on Cyanide Security (https://gitlab.com/cyanidesec). His commit history (view here: https://gitlab.com/d-nni3l#activity) is full of updates to Markdown files (*.md). Markdown, if you don't know, is basically flavored text files. You can see examples of them with "README.MD", "LICENSE.MD", etc.

The group, Code at MMS (https://gitlab.com/codeatmms) has only one project (which is the one I'm posting this very important issue). Is that really a use of coding?

Overall, Daniel is a fraud who says he can code. He steals other codes on sites and makes groups and hosts files on GitHub and GitLab just for websites. Before this issue gets shut down or broken, I would recommend you think twice about your thought of Daniel and if you still want to keep this kind of thing going where he treats everyone as a script kiddie.

(P.S. A script kiddie is an uneducated twat when it comes to coding and uses scripts/programs from other developers to deface, recreate, and attack other servers, computer systems, projects, programs, and networks.)

**Comment by d-nni3l** [comment]
@Incrested This project was essentially abandoned before it started. If you want to, go ahead and read my response on the Gitlab repository for code@mms.
